### ISSUE TITLE
[Firefox] Link outline rendering issues

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-link#183]
So this is how outline is rendered on Firefox:

![selection_013](https://user-images.githubusercontent.com/247363/37409773-6ca27bc4-279f-11e8-89a5-e3ddde4a7907.png)

The same content on Chrome:

![selection_014](https://user-images.githubusercontent.com/247363/37409799-7bd842ea-279f-11e8-9ba0-88e0fe0322b7.png)

**Comment by Reinmar** [comment]
Kinda looks that we shouldn't use the outline. Maybe box-shadow then?

**Comment by jodator** [comment]
@Reinmar it looks like it does the trick:

FF:
![selection_015](https://user-images.githubusercontent.com/247363/37410489-0dedc0e6-27a1-11e8-80e4-f2366cadf70a.png)

Chrome:
![selection_016](https://user-images.githubusercontent.com/247363/37410506-13e750fc-27a1-11e8-8dd6-20f4a82d6534.png)

(both have background disabled to show box shadow)

I've used:
```css
.ck-link_selected {
    box-shadow: var(--ck-color-link-selected-background) 0px 0px 0 1px;
}
```
